# Generated by Django 5.2.13 on 2026-05-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('HATCHBACK', 'Hatchback'), ('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('MUV', 'MUV'), ('MPV', 'MPV'), ('LUXURY', 'Luxury'), ('TEMPO', 'Tempo Traveller')], default='SEDAN', max_length=20),
        ),
    ]
